on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  update-version:
    name: Test
    runs-on: ubuntu-latest
    # prevent wf to run on tags not on main
#    if: github.base_ref == 'refs/heads/main'
    steps:
      - name: checkout code from repos
        uses: actions/checkout@v2
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo "${branch}"
