---
name: Publish PR preview

# Controls when the action will run.
on: [ pull_request_target ]

jobs:
  deploy:
    name: Build and publish PR preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repos
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge # required to pull the PR code instead of the main one
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info

      - name: generate PR slug
        shell: sh
        id: generate_pr_slug
        run: echo "::set-output name=slug::PR-${{ github.event.number }}"

      - name: Deploy Preview
        uses: JamesIves/github-pages-deploy-action@6ce741f5d4e01e15f9ea5ec96df1a43f522c330f #4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
          target-folder: ${{ steps.generate_pr_slug.outputs.slug }}
          commit-message: Preview for ${{ steps.generate_pr_slug.outputs.slug }}
          single-commit: true

      - name: Add comment with link to preview doc
        uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443 #v2.2.0
        with:
          header: preview
          recreate: true
          message: |
            [Doc preview for this PR #${{ github.event.number }} is available](https://${{ env.CI_REPOSITORY_OWNER }}.github.io/${{ env.CI_REPOSITORY_NAME }}/${{ steps.generate_pr_slug.outputs.slug }})

