name: Check remote assets
on: [push, workflow_dispatch]
jobs:
  check-remote-assets:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          import {WORKING_INDEX, FAILING_INDEX} from './remotes.js'
          console.log('WORKING_INDEX', WORKING_INDEX)
          console.log('FAILING_INDEX', FAILING_INDEX)
